In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
import math
import pickle as pk

In [2]:
train = pd.read_csv('csv/MediaPipe/train_nose_184.csv')
test = pd.read_csv('csv/MediaPipe/test_nose_184.csv')

In [3]:
train.head()

V0        V1        V2        V3        V4        V5        V6  \
0 -0.297426 -0.473132 -0.650654 -0.849423 -0.996441 -1.067820 -1.156753   
1 -0.376166 -0.346421 -0.302813 -0.230802 -0.156279 -0.012831 -0.047162   
2 -0.211765 -0.378358 -0.543208 -0.721045 -0.848202 -0.891288 -0.972356   
3 -1.666382 -1.610004 -1.549013 -1.474557 -1.404201 -1.306937 -1.306823   
4  0.337538  0.231630  0.233884  0.314808  0.399223  0.492313  0.509209   

         V7        V8        V9  ...      V175      V176      V177      V178  \
0 -0.100666 -0.170887 -1.089498  ...  0.347779  0.460423  0.564430  0.247298   
1 -0.368209 -0.370542 -0.099004  ...  0.375510  0.366770  0.380406  0.184203   
2  0.018882 -0.076024 -0.927402  ... -0.581318 -0.561493 -0.541889 -0.838319   
3 -1.708192 -1.693661 -1.350910  ... -1.098112 -1.169724 -1.140300 -0.307483   
4  0.551466  0.482724  0.460351  ... -0.446302 -0.359649 -0.246551 -0.183265   

       V179      V180      V181      V182      V183    y  
0  0.024115  0.050741  0.146586  0.025320  0.118462  0.0  
1  0.324787  0.366871  0.291419  0.377346  0.446578  0.0  
2 -0.860101 -0.761671 -0.756214 -0.759488 -0.585651  0.0  
3 -0.946832 -0.953239 -0.573587 -0.936231 -0.595380  0.0  
4 -0.616226 -0.627338 -0.382590 -0.586211 -0.511034  0.0  

[5 rows x 185 columns]

In [4]:
train.isna().sum()

V0      0
V1      0
V2      0
V3      0
V4      0
       ..
V180    0
V181    0
V182    0
V183    0
y       0
Length: 185, dtype: int64

In [5]:
train.y.nunique()

5

In [6]:
#train.groupby('y').mean().hist()

In [7]:
y_train = train['y'].astype('int')
train.drop('y', axis=1, inplace=True)

y_test = test['y'].astype('int')
test.drop('y', axis=1, inplace=True)

In [8]:
train.head(3)

V0        V1        V2        V3        V4        V5        V6  \
0 -0.297426 -0.473132 -0.650654 -0.849423 -0.996441 -1.067820 -1.156753   
1 -0.376166 -0.346421 -0.302813 -0.230802 -0.156279 -0.012831 -0.047162   
2 -0.211765 -0.378358 -0.543208 -0.721045 -0.848202 -0.891288 -0.972356   

         V7        V8        V9  ...      V174      V175      V176      V177  \
0 -0.100666 -0.170887 -1.089498  ...  0.052607  0.347779  0.460423  0.564430   
1 -0.368209 -0.370542 -0.099004  ...  0.372150  0.375510  0.366770  0.380406   
2  0.018882 -0.076024 -0.927402  ... -0.735086 -0.581318 -0.561493 -0.541889   

       V178      V179      V180      V181      V182      V183  
0  0.247298  0.024115  0.050741  0.146586  0.025320  0.118462  
1  0.184203  0.324787  0.366871  0.291419  0.377346  0.446578  
2 -0.838319 -0.860101 -0.761671 -0.756214 -0.759488 -0.585651  

[3 rows x 184 columns]

In [9]:
y_train

0        0
1        0
2        0
3        0
4        0
        ..
19298    4
19299    4
19300    4
19301    4
19302    4
Name: y, Length: 19303, dtype: int32

In [10]:
print("Size of train", len(train))
print("Size of test", len(test))

Size of train 19303
Size of test 4828


In [11]:
y_train.value_counts().reset_index().sort_values(by='y')

index     y
4      4  2474
3      0  2902
2      3  3439
1      2  4298
0      1  6190

In [12]:
y_test.value_counts().reset_index().sort_values(by='y')

index     y
4      4   644
3      0   693
2      3   864
1      2  1092
0      1  1535

In [13]:
#scaler = StandardScaler().fit(train)

In [14]:
#X_train = scaler.transform(train)
#X_test = scaler.transform(test)

In [15]:
#X_train

In [16]:
#X_test

In [17]:
#std = np.sqrt(scaler.var_)

In [18]:
#np.save('std.npy', std)

In [19]:
#np.save('mean.npy', scaler.mean_)

In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import GradientBoostingClassifier

In [21]:
#model = GradientBoostingClassifier()

In [22]:
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [28]:
param_grid = {
    'n_estimators': [3], #10, 50, 100, 500
    'subsample': [0.5, 0.7, 1.0],
    'learning_rate': [0.0001, 0.001, 0.01, 0.1, 1.0],
    'max_depth': [3, 7, 9],
    'max_features': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
}

#

In [29]:
#grid_search = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='accuracy')

In [50]:
#grid_result = grid_search.fit(train, y_train)

In [51]:
#print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

In [52]:
# summarize all scores that were evaluated
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']
# for mean, stdev, param in zip(means, stds, params):
#     print("%f (%f) with: %r" % (mean, stdev, param))

In [23]:
model = GradientBoostingClassifier(n_estimators=500, 
                                   subsample=0.6, 
                                   learning_rate=0.01, 
                                   max_depth=10, 
                                   max_features='sqrt', 
                                   loss='deviance',
                                   min_samples_split=4,
                                   min_samples_leaf=2,
                                  )

In [24]:
%%time
model.fit(train, y_train)

C:\Users\Nur\AppData\Roaming\Python\Python39\site-packages\sklearn\ensemble\_gb.py:310: FutureWarning: The loss parameter name 'deviance' was deprecated in v1.1 and will be removed in version 1.3. Use the new parameter name 'log_loss' which is equivalent.
  warnings.warn(


CPU times: total: 6min 38s
Wall time: 6min 39s


GradientBoostingClassifier(learning_rate=0.01, loss='deviance', max_depth=10,
                           max_features='sqrt', min_samples_leaf=2,
                           min_samples_split=4, n_estimators=500,
                           subsample=0.6)

In [25]:
def evaluate_model(model, X, y):
    # define the evaluation procedure
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
    # evaluate the model and collect the results
    scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
    return scores

In [26]:
#scores = evaluate_model(model, test, y_test)

In [27]:
y_pred = model.predict(test)

In [28]:
print(confusion_matrix(y_pred, y_test))

[[ 201   23   59   62   27]
 [ 148 1222  154  151   58]
 [ 205  165  686  325   76]
 [  95   76  168  300   33]
 [  44   49   25   26  450]]


In [29]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.29      0.54      0.38       372
           1       0.80      0.71      0.75      1733
           2       0.63      0.47      0.54      1457
           3       0.35      0.45      0.39       672
           4       0.70      0.76      0.73       594

    accuracy                           0.59      4828
   macro avg       0.55      0.58      0.56      4828
weighted avg       0.63      0.59      0.60      4828



In [30]:
model

GradientBoostingClassifier(learning_rate=0.01, loss='deviance', max_depth=10,
                           max_features='sqrt', min_samples_leaf=2,
                           min_samples_split=4, n_estimators=500,
                           subsample=0.6)

In [31]:
import pickle as pk

with open('model9_nose_boost185', 'wb') as f:
    pk.dump(model, f)

In [34]:
with open("model9_nose_boost185", "rb") as f:
    model_boost = pk.load(f)
    f.close()

In [35]:
model_boost

GradientBoostingClassifier(learning_rate=0.01, loss='deviance', max_depth=10,
                           max_features='sqrt', min_samples_leaf=2,
                           min_samples_split=4, n_estimators=500,
                           subsample=0.6)