In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, BatchNormalization
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler

In [2]:
train = pd.read_csv("csv/MediaPipe/train_nose_184_cropped_8emotion.csv")
test = pd.read_csv("csv/MediaPipe/test_nose_184_cropped_8emotion.csv")

In [3]:
X_train = train.drop("y", axis=1)
y_train = train["y"]

In [4]:
X_train.head()

V0        V1        V2        V3        V4        V5        V6   
0  0.858615  0.825387  0.774809  0.722167  0.683341  0.622038  0.637829  \
1  0.096722  0.149883  0.210612  0.319156  0.418227  0.497839  0.541343   
2  0.473112  0.523687  0.552028  0.565787  0.565893  0.551039  0.555815   
3  0.309079  0.375406  0.384272  0.380315  0.366400  0.362447  0.347218   
4 -1.101826 -1.009243 -0.951218 -0.919509 -0.924826 -1.172693 -0.959095   

         V7        V8        V9  ...      V174      V175      V176      V177   
0  0.836358  0.852549  0.652842  ... -0.865015 -1.172562 -1.154096 -0.977151  \
1  0.100233  0.088916  0.482932  ... -1.534856 -1.471007 -1.185580 -0.782679   
2  0.392295  0.417814  0.560580  ... -0.446299 -0.564322 -0.477542 -0.251394   
3  0.189191  0.221457  0.355136  ... -0.640944 -0.717027 -0.590346 -0.400920   
4 -1.283163 -1.222229 -0.936492  ...  0.627450  1.586391  1.996306  2.072256   

       V178      V179      V180      V181      V182      V183  
0 -0.055176  0.001249 -0.376445 -0.350426 -0.564401 -0.199428  
1 -0.815739 -0.665111 -1.123142 -1.295908 -1.337882 -1.239920  
2 -0.221608 -0.713836 -0.674373 -0.389941 -0.550756 -0.125124  
3 -0.934616 -0.843371 -0.805098 -0.905101 -0.698863 -0.532940  
4  0.253576  0.413474  0.526993  0.441075  0.518837  0.031181  

[5 rows x 184 columns]

In [5]:
X_test = test.drop("y", axis=1)
y_test = test["y"]

In [6]:
X_test.head()

V0        V1        V2        V3        V4        V5        V6   
0  0.159450  0.092518  0.086819  0.154854  0.238034  0.333146  0.352455  \
1 -0.400809 -0.612326 -0.846924 -1.123699 -1.326612 -1.518536 -1.522389   
2 -0.502503 -0.492592 -0.485455 -0.490099 -0.490608 -0.497583 -0.482947   
3  0.390620  0.276295  0.191752  0.154475  0.173530  0.242542  0.219779   
4  0.623326  0.610391  0.623909  0.708758  0.808036  1.023063  0.956635   

         V7        V8        V9  ...      V174      V175      V176      V177   
0  0.293689  0.254175  0.302080  ...  0.019967 -0.338051 -0.493751 -0.578819  \
1 -0.179601 -0.260954 -1.450057  ...  0.305114  1.107279  1.316345  1.345083   
2 -0.547429 -0.516347 -0.488743  ...  1.359535  0.452661 -0.024015 -0.343805   
3  0.548233  0.493273  0.196168  ...  0.568672  0.617128  0.655726  0.600655   
4  0.716895  0.685492  0.884659  ... -0.604208 -0.331344 -0.055060  0.157113   

       V178      V179      V180      V181      V182      V183  
0  0.831001  0.745222  0.570051  0.600601  0.362707  0.325782  
1 -0.292861 -0.132299  0.132239 -0.024831  0.192830 -0.158113  
2  2.930198  2.787786  2.453542  2.520344  2.099021  2.624696  
3  1.547585  1.740032  1.269748  1.157858  0.968095  0.232494  
4 -0.340324 -0.342361 -0.545417 -0.678132 -0.572869 -0.510297  

[5 rows x 184 columns]

In [7]:
n_classes = y_train.nunique()
n_classes

8

In [8]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [9]:
y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [10]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [11]:
# scaler = StandardScaler().fit(X_train)
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

In [12]:
# std = np.sqrt(scaler.var_)
# np.save("std5.npy", std)
# np.save("mean5.npy", scaler.mean_)

In [21]:
from keras.regularizers import l2, l1
from keras.callbacks import LearningRateScheduler
from keras.optimizers import RMSprop, SGD, Adagrad, Adam
from keras.layers import Dropout

In [29]:
# def lr_decay(epoch):
#     initial_lr = 0.01
#     lr = initial_lr * 1.0 / (1.0 + 0.001 * epoch)
#     return lr

# def lr_decay(epoch):
#     lr = 0.0003
#     if epoch > 1:
#         lr = 0.0001
#     if epoch > 10:
#         lr = 0.00005
#     if epoch > 40:
#         lr = 0.00003
#     if epoch > 50:
#         lr = 0.00001
#     if epoch > 90:
#         lr = 0.000005
#     if epoch > 120:
#         lr = 0.000003
#     if epoch > 130:
#         lr = 0.000001
#     return lr

def lr_decay(epoch):
    lr = 0.0003
    if epoch > 1:
        lr = 0.0001
    if epoch > 26:
        lr = 0.00005
    if epoch > 40:
        lr = 0.00003
    if epoch > 50:
        lr = 0.00001
    if epoch > 90:
        lr = 0.000005
    if epoch > 120:
        lr = 0.000003
    if epoch > 130:
        lr = 0.000001
    if epoch > 150:
        lr = 0.0000005
    if epoch > 160:
        lr = 0.0000003
    if epoch > 170:
        lr = 0.0000001
    if epoch > 180:
        lr = 0.00000005
    if epoch > 190:
        lr = 0.00000001
    return lr * 10

In [30]:
lr_scheduler = LearningRateScheduler(lr_decay)

In [31]:
# model = Sequential()
# model.add(Dense(32, input_dim=24, activation='elu', kernel_regularizer=l2(0.01)))
# model.add(Dense(64, activation='elu', kernel_regularizer=l2(0.01)))
# model.add(Dense(128, activation='elu', kernel_regularizer=l2(0.01)))
# model.add(Dense(5, activation='softmax'))

model = Sequential()

model.add(Dense(64, input_dim=X_train.shape[1], activation='elu'))

model.add(BatchNormalization())

model.add(Dropout(0.2))

model.add(Dense(128, activation='elu', kernel_regularizer=l2(0.01)))

model.add(BatchNormalization())

model.add(Dropout(0.3))

model.add(Dense(256, activation='elu', kernel_regularizer=l2(0.01)))

model.add(BatchNormalization())

model.add(Dense(512, activation='relu', kernel_regularizer=l2(0.01)))

#model.add(Dropout(0.4))

model.add(Dense(n_classes, activation='softmax'))

In [32]:
optimizer = SGD()

In [33]:
model.compile(loss='categorical_crossentropy',
              optimizer=optimizer,
              metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 64)                11840     
                                                                 
 batch_normalization_6 (Batc  (None, 64)               256       
 hNormalization)                                                 
                                                                 
 dropout_4 (Dropout)         (None, 64)                0         
                                                                 
 dense_9 (Dense)             (None, 128)               8320      
                                                                 
 batch_normalization_7 (Batc  (None, 128)              512       
 hNormalization)                                                 
                                                                 
 dropout_5 (Dropout)         (None, 128)              

In [35]:
history = model.fit(
            X_train, y_train,
            validation_data=(X_test, y_test),
            epochs=200,
            batch_size=32,
            callbacks=[lr_scheduler]
                   )

Epoch 1/200
657/657 [==============================] - 8s 11ms/step - loss: 4.3859 - accuracy: 0.3018 - val_loss: 3.9718 - val_accuracy: 0.3979 - lr: 0.0030
Epoch 2/200
657/657 [==============================] - 7s 11ms/step - loss: 4.0038 - accuracy: 0.3586 - val_loss: 3.7648 - val_accuracy: 0.4142 - lr: 0.0030
Epoch 3/200
657/657 [==============================] - 7s 11ms/step - loss: 3.8355 - accuracy: 0.3756 - val_loss: 3.6964 - val_accuracy: 0.4119 - lr: 0.0010
Epoch 4/200
657/657 [==============================] - 7s 11ms/step - loss: 3.7671 - accuracy: 0.3763 - val_loss: 3.6373 - val_accuracy: 0.4171 - lr: 0.0010
Epoch 5/200
657/657 [==============================] - 7s 11ms/step - loss: 3.7020 - accuracy: 0.3825 - val_loss: 3.5801 - val_accuracy: 0.4154 - lr: 0.0010
Epoch 6/200
657/657 [==============================] - 7s 11ms/step - loss: 3.6418 - accuracy: 0.3842 - val_loss: 3.5200 - val_accuracy: 0.4208 - lr: 0.0010
Epoch 7/200
657/657 [==============================] - 8s 

657/657 [==============================] - 7s 11ms/step - loss: 2.4023 - accuracy: 0.4229 - val_loss: 2.3542 - val_accuracy: 0.4408 - lr: 1.0000e-04
Epoch 53/200
657/657 [==============================] - 7s 11ms/step - loss: 2.3948 - accuracy: 0.4312 - val_loss: 2.3513 - val_accuracy: 0.4430 - lr: 1.0000e-04
Epoch 54/200
657/657 [==============================] - 7s 11ms/step - loss: 2.3959 - accuracy: 0.4264 - val_loss: 2.3485 - val_accuracy: 0.4436 - lr: 1.0000e-04
Epoch 55/200
657/657 [==============================] - 7s 11ms/step - loss: 2.3950 - accuracy: 0.4287 - val_loss: 2.3467 - val_accuracy: 0.4419 - lr: 1.0000e-04
Epoch 56/200
657/657 [==============================] - 7s 11ms/step - loss: 2.3877 - accuracy: 0.4311 - val_loss: 2.3457 - val_accuracy: 0.4413 - lr: 1.0000e-04
Epoch 57/200
657/657 [==============================] - 7s 11ms/step - loss: 2.3871 - accuracy: 0.4277 - val_loss: 2.3422 - val_accuracy: 0.4419 - lr: 1.0000e-04
Epoch 58/200
657/657 [===================

Epoch 103/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2997 - accuracy: 0.4262 - val_loss: 2.2536 - val_accuracy: 0.4411 - lr: 5.0000e-05
Epoch 104/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2990 - accuracy: 0.4282 - val_loss: 2.2531 - val_accuracy: 0.4419 - lr: 5.0000e-05
Epoch 105/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2951 - accuracy: 0.4334 - val_loss: 2.2527 - val_accuracy: 0.4413 - lr: 5.0000e-05
Epoch 106/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2971 - accuracy: 0.4315 - val_loss: 2.2505 - val_accuracy: 0.4413 - lr: 5.0000e-05
Epoch 107/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2937 - accuracy: 0.4268 - val_loss: 2.2503 - val_accuracy: 0.4433 - lr: 5.0000e-05
Epoch 108/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2896 - accuracy: 0.4314 - val_loss: 2.2487 - val_accuracy: 0.4416 - lr: 5.0000e-05
Epoch 109/200
657/657 

657/657 [==============================] - 7s 11ms/step - loss: 2.2702 - accuracy: 0.4306 - val_loss: 2.2244 - val_accuracy: 0.4448 - lr: 5.0000e-06
Epoch 154/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2672 - accuracy: 0.4315 - val_loss: 2.2249 - val_accuracy: 0.4453 - lr: 5.0000e-06
Epoch 155/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2677 - accuracy: 0.4281 - val_loss: 2.2250 - val_accuracy: 0.4425 - lr: 5.0000e-06
Epoch 156/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2700 - accuracy: 0.4289 - val_loss: 2.2242 - val_accuracy: 0.4433 - lr: 5.0000e-06
Epoch 157/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2700 - accuracy: 0.4319 - val_loss: 2.2238 - val_accuracy: 0.4422 - lr: 5.0000e-06
Epoch 158/200
657/657 [==============================] - 7s 11ms/step - loss: 2.2693 - accuracy: 0.4293 - val_loss: 2.2240 - val_accuracy: 0.4430 - lr: 5.0000e-06
Epoch 159/200
657/657 [=============

In [36]:
score = model.evaluate(X_test, y_test, batch_size=32)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

110/110 [==============================] - 1s 6ms/step - loss: 2.2228 - accuracy: 0.4430
Test loss: 2.2228288650512695
Test accuracy: 0.4430488049983978


In [37]:
y_pred = model.predict(X_test, batch_size=32)

110/110 [==============================] - 0s 3ms/step


In [38]:
y_pred

array([[0.04138707, 0.06039013, 0.11357411, ..., 0.10891047, 0.15546967,
        0.1712307 ],
       [0.14307354, 0.07237261, 0.02740956, ..., 0.5379369 , 0.09588666,
        0.04353119],
       [0.05607066, 0.00543116, 0.03357522, ..., 0.01596706, 0.04808548,
        0.45700195],
       ...,
       [0.15938637, 0.16355582, 0.03104691, ..., 0.22989476, 0.14316382,
        0.17440644],
       [0.1702728 , 0.09815435, 0.15182802, ..., 0.2694157 , 0.1877216 ,
        0.02708928],
       [0.02271451, 0.05910092, 0.10607969, ..., 0.02412572, 0.05790017,
        0.01738121]], dtype=float32)

In [39]:
y_pred = np.argmax(y_pred, axis=1)

In [40]:
y_pred

array([4, 5, 7, ..., 5, 5, 4], dtype=int64)

In [41]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [42]:
y_test = np.argmax(y_test, axis=1)

In [43]:
print(confusion_matrix(y_pred, y_test))

[[142  51  40  31   3  51  36  19]
 [ 46 145  20  13  40  72  22  27]
 [ 27   8  47  10  13  12  14   9]
 [ 13   3  17  60   1  11  15  35]
 [ 20  44  50  38 511  27  23  35]
 [ 79  85  80  76  58 339 157  96]
 [ 19  12  15  20   8  25  65   4]
 [ 30  17  31 135  18  58  32 243]]


In [26]:
print(confusion_matrix(y_pred, y_test))

[[ 219   31   75  100   35]
 [ 123 1290  147  117   71]
 [ 177  112  637  284   78]
 [ 121   53  187  337   26]
 [  53   49   46   26  434]]


In [44]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.38      0.38      0.38       373
           1       0.40      0.38      0.39       385
           2       0.16      0.34      0.21       140
           3       0.16      0.39      0.22       155
           4       0.78      0.68      0.73       748
           5       0.57      0.35      0.43       970
           6       0.18      0.39      0.24       168
           7       0.52      0.43      0.47       564

    accuracy                           0.44      3503
   macro avg       0.39      0.42      0.39      3503
weighted avg       0.51      0.44      0.46      3503



In [59]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.32      0.48      0.38       461
           1       0.83      0.74      0.78      1714
           2       0.63      0.48      0.54      1428
           3       0.35      0.50      0.41       610
           4       0.66      0.70      0.68       615

    accuracy                           0.60      4828
   macro avg       0.56      0.58      0.56      4828
weighted avg       0.64      0.60      0.61      4828



In [27]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.32      0.48      0.38       460
           1       0.84      0.74      0.79      1748
           2       0.58      0.49      0.54      1288
           3       0.39      0.47      0.42       724
           4       0.67      0.71      0.69       608

    accuracy                           0.60      4828
   macro avg       0.56      0.58      0.56      4828
weighted avg       0.63      0.60      0.61      4828



In [72]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.47      0.46      0.47       463
           1       0.57      0.60      0.58       387
           2       0.39      0.48      0.43       267
           3       0.38      0.48      0.42       368
           4       0.90      0.87      0.89       750
           5       0.88      0.75      0.81       880
           6       0.45      0.46      0.45       426
           7       0.53      0.51      0.52       601

    accuracy                           0.62      4142
   macro avg       0.57      0.58      0.57      4142
weighted avg       0.64      0.62      0.63      4142



In [34]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.50      0.47      0.48       475
           1       0.55      0.61      0.58       370
           2       0.37      0.48      0.42       256
           3       0.40      0.47      0.43       393
           4       0.90      0.87      0.88       750
           5       0.89      0.75      0.81       894
           6       0.45      0.46      0.46       424
           7       0.54      0.54      0.54       580

    accuracy                           0.62      4142
   macro avg       0.58      0.58      0.58      4142
weighted avg       0.64      0.62      0.63      4142



In [60]:
model.save('mlp2_dataset_60%_5emotions.h5')