## Import need libraries and data cleaning

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

V1     V2     V3     V4     V5     V6     V7     V8     V9    V10  ...  \
0  10.32  30.41  10.52  21.10  67.36  30.07  27.46  15.82  14.22  48.17  ...   
1   6.58  27.29   7.28  28.64  57.72  63.01  35.81  22.18  23.25  46.49  ...   
2  10.50  35.00   8.56  31.02  61.85  49.37  35.36  36.38  29.74  61.85  ...   
3   6.20  29.43   5.39  27.29  50.45  44.05  26.93  25.09  25.30  38.08  ...   
4  15.13  34.93  13.54  35.23  61.66  63.32  39.60  28.75  28.70  47.41  ...   

     V16    V17    V18    V19    V20    V21    V22    V23    V24    y  
0  36.67  29.15  18.03   9.06  25.50  34.93   3.76  56.89  52.01  0.0  
1  45.71  48.27  49.37  23.09  22.67  40.50  10.05  45.89  48.04  0.0  
2  44.64  44.28  40.72  18.44  31.89  49.16   5.69  41.79  39.32  0.0  
3  37.48  37.70  30.68  17.03  22.63  27.51   8.12  35.34  33.06  0.0  
4  42.05  48.88  50.54  25.00  22.20  42.20  12.03  53.15  51.92  0.0  

[5 rows x 25 columns]

In [4]:
df.isna().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
V6     0
V7     0
V8     0
V9     0
V10    0
V11    0
V12    0
V13    0
V14    0
V15    0
V16    0
V17    0
V18    0
V19    0
V20    0
V21    0
V22    0
V23    0
V24    0
y      0
dtype: int64

In [5]:
df.describe()

V1            V2            V3            V4            V5  \
count  24176.000000  24176.000000  24176.000000  24176.000000  24176.000000   
mean       9.646401     30.478495      9.675045     30.520949     54.579587   
std        3.148161      5.246700      3.157097      5.229381     12.528098   
min        1.000000     11.000000      0.000000     11.400000      2.000000   
25%        7.500000     27.070000      7.500000     27.170000     46.530000   
50%        9.500000     30.150000      9.500000     30.230000     54.330000   
75%       11.540000     33.380000     11.610000     33.540000     62.390000   
max       24.580000     54.420000     24.050000     54.450000    101.490000   

                 V6            V7            V8            V9           V10  \
count  24176.000000  24176.000000  24176.000000  24176.000000  24176.000000   
mean      55.117870     32.671571     25.100918     25.213413     40.484568   
std       12.408097      5.219167      5.781606      5.787050      9.514951   
min        1.000000     16.120000      6.720000      6.440000      5.660000   
25%       47.160000     29.070000     21.060000     21.140000     33.970000   
50%       55.040000     32.250000     24.740000     24.910000     39.850000   
75%       63.030000     36.060000     28.910000     29.020000     46.490000   
max      103.590000     60.220000     49.650000     50.120000     81.120000   

       ...           V16           V17           V18           V19  \
count  ...  24176.000000  24176.000000  24176.000000  24176.000000   
mean   ...     44.966832     45.609038     42.321066     20.839823   
std    ...     11.011579     10.303425     10.112174      5.094046   
min    ...      3.160000      8.060000      5.000000      2.240000   
25%    ...     37.360000     38.330000     35.510000     17.260000   
50%    ...     44.010000     44.410000     41.980000     20.400000   
75%    ...     51.920000     52.000000     48.840000     24.080000   
max    ...     97.060000     92.480000     83.190000     41.010000   

                V20           V21           V22           V23           V24  \
count  24176.000000  24176.000000  24176.000000  24176.000000  24176.000000   
mean      20.853924     32.432340      9.405581     50.734225     50.844608   
std        5.920146      7.718755      8.668751      8.554448      8.543110   
min        2.000000      7.000000      0.000000     22.800000     18.680000   
25%       16.970000     27.070000      2.540000     45.100000     45.100000   
50%       20.520000     31.950000      6.610000     50.250000     50.360000   
75%       24.410000     37.160000     14.020000     56.040000     56.140000   
max       47.170000     66.370000     63.010000     93.090000     95.020000   

                  y  
count  24176.000000  
mean       1.833182  
std        1.286896  
min        0.000000  
25%        1.000000  
50%        2.000000  
75%        3.000000  
max        4.000000  

[8 rows x 25 columns]

In [6]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

## Train Test Split and Evaluation of models

In [7]:
X_train = train.drop('y', axis=1)
y_train = train['y']


In [31]:
X_test = test.drop('y', axis=1)
y_test = test['y']


In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [33]:
classifiers = {"LogisiticRegression": LogisticRegression(),
               "KNearest": KNeighborsClassifier(),
               "Support Vector Classifier": SVC(),
               "DecisionTreeClassifier": DecisionTreeClassifier(), 
               "RandomForest": RandomForestClassifier()}

for key, classifier in classifiers.items():
    classifier.fit(X_train, y_train)
    print("Classifiers: ", classifier.__class__.__name__, "Has a training score of", round(classifier.score(X_test, y_test)*100), "% accuracy score")
    

C:\Users\aliha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Classifiers:  LogisticRegression Has a training score of 52 % accuracy score
Classifiers:  KNeighborsClassifier Has a training score of 51 % accuracy score
Classifiers:  SVC Has a training score of 56 % accuracy score
Classifiers:  DecisionTreeClassifier Has a training score of 46 % accuracy score
Classifiers:  RandomForestClassifier Has a training score of 58 % accuracy score


# Finding the best hyperparameters of models

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline


# Finding the best hyperparameters of models

## Logistic regression

In [34]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [35]:
lr_param_grid = {
    'C': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 10.0]
}


In [36]:
lr_grid= GridSearchCV(LogisticRegression(), lr_param_grid)

In [37]:
lr_grid.fit(X_train, y_train)

C:\Users\aliha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\aliha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

C:\Users\aliha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\aliha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

C:\Users\aliha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\aliha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 10.0]})

In [38]:
lr_grid.best_estimator_

LogisticRegression()

In [39]:
lr_grid_pred = lr_grid.predict(X_test)

In [40]:
print(confusion_matrix(y_test, lr_grid_pred))

[[ 291  198  206  195   68]
 [  92 1329  150  130   73]
 [  93  177  609  286   68]
 [ 164  268  331  406   78]
 [  54  102   77   61  537]]


In [41]:
print(classification_report(y_test, lr_grid_pred))

              precision    recall  f1-score   support

         0.0       0.42      0.30      0.35       958
         1.0       0.64      0.75      0.69      1774
         2.0       0.44      0.49      0.47      1233
         3.0       0.38      0.33      0.35      1247
         4.0       0.65      0.65      0.65       831

    accuracy                           0.52      6043
   macro avg       0.51      0.50      0.50      6043
weighted avg       0.51      0.52      0.52      6043



## SVC

In [42]:
svc_param_grid = [{
                    'svc__C': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 10.0],
                    'svc__kernel': ['linear']
                  },
                 {
                    'svc__C': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 10.0],
                    'svc__gamma': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 10.0],
                    'svc__kernel': ['rbf']
                 }
]

In [43]:

svc_clf = make_pipeline(StandardScaler(), SVC(random_state=1))



In [45]:
svc_grid = GridSearchCV(estimator=svc_clf, param_grid=svc_param_grid, verbose=3)

In [46]:
svc_grid.fit(X_train, y_train)

Fitting 5 folds for each of 56 candidates, totalling 280 fits
[CV 1/5] END ..svc__C=0.001, svc__kernel=linear;, score=0.535 total time=  41.4s
[CV 2/5] END ..svc__C=0.001, svc__kernel=linear;, score=0.514 total time=  40.6s
[CV 3/5] END ..svc__C=0.001, svc__kernel=linear;, score=0.511 total time=  39.6s
[CV 4/5] END ..svc__C=0.001, svc__kernel=linear;, score=0.526 total time=  39.1s
[CV 5/5] END ..svc__C=0.001, svc__kernel=linear;, score=0.523 total time=  37.6s
[CV 1/5] END ...svc__C=0.01, svc__kernel=linear;, score=0.551 total time=  34.8s
[CV 2/5] END ...svc__C=0.01, svc__kernel=linear;, score=0.536 total time=  33.0s
[CV 3/5] END ...svc__C=0.01, svc__kernel=linear;, score=0.529 total time=  33.9s
[CV 4/5] END ...svc__C=0.01, svc__kernel=linear;, score=0.547 total time=  36.0s
[CV 5/5] END ...svc__C=0.01, svc__kernel=linear;, score=0.539 total time=  34.1s
[CV 1/5] END ...svc__C=0.05, svc__kernel=linear;, score=0.558 total time=  36.0s
[CV 2/5] END ...svc__C=0.05, svc__kernel=linear

[CV 4/5] END svc__C=0.01, svc__gamma=0.5, svc__kernel=rbf;, score=0.298 total time=  35.2s
[CV 5/5] END svc__C=0.01, svc__gamma=0.5, svc__kernel=rbf;, score=0.298 total time=  35.2s
[CV 1/5] END svc__C=0.01, svc__gamma=1.0, svc__kernel=rbf;, score=0.298 total time=  40.9s
[CV 2/5] END svc__C=0.01, svc__gamma=1.0, svc__kernel=rbf;, score=0.298 total time=  40.9s
[CV 3/5] END svc__C=0.01, svc__gamma=1.0, svc__kernel=rbf;, score=0.298 total time=  40.9s
[CV 4/5] END svc__C=0.01, svc__gamma=1.0, svc__kernel=rbf;, score=0.298 total time=  40.9s
[CV 5/5] END svc__C=0.01, svc__gamma=1.0, svc__kernel=rbf;, score=0.298 total time=  40.8s
[CV 1/5] END svc__C=0.01, svc__gamma=10.0, svc__kernel=rbf;, score=0.298 total time=  49.4s
[CV 2/5] END svc__C=0.01, svc__gamma=10.0, svc__kernel=rbf;, score=0.298 total time=  49.3s
[CV 3/5] END svc__C=0.01, svc__gamma=10.0, svc__kernel=rbf;, score=0.298 total time=  49.2s
[CV 4/5] END svc__C=0.01, svc__gamma=10.0, svc__kernel=rbf;, score=0.298 total time=  4

[CV 4/5] END svc__C=0.5, svc__gamma=0.01, svc__kernel=rbf;, score=0.558 total time=  23.6s
[CV 5/5] END svc__C=0.5, svc__gamma=0.01, svc__kernel=rbf;, score=0.556 total time=  23.4s
[CV 1/5] END svc__C=0.5, svc__gamma=0.05, svc__kernel=rbf;, score=0.580 total time=  23.3s
[CV 2/5] END svc__C=0.5, svc__gamma=0.05, svc__kernel=rbf;, score=0.558 total time=  23.0s
[CV 3/5] END svc__C=0.5, svc__gamma=0.05, svc__kernel=rbf;, score=0.563 total time=  23.1s
[CV 4/5] END svc__C=0.5, svc__gamma=0.05, svc__kernel=rbf;, score=0.574 total time=  23.3s
[CV 5/5] END svc__C=0.5, svc__gamma=0.05, svc__kernel=rbf;, score=0.564 total time=  23.2s
[CV 1/5] END svc__C=0.5, svc__gamma=0.1, svc__kernel=rbf;, score=0.586 total time=  24.6s
[CV 2/5] END svc__C=0.5, svc__gamma=0.1, svc__kernel=rbf;, score=0.556 total time=  24.5s
[CV 3/5] END svc__C=0.5, svc__gamma=0.1, svc__kernel=rbf;, score=0.565 total time=  24.6s
[CV 4/5] END svc__C=0.5, svc__gamma=0.1, svc__kernel=rbf;, score=0.576 total time=  24.7s
[CV

[CV 5/5] END svc__C=10.0, svc__gamma=1.0, svc__kernel=rbf;, score=0.465 total time= 1.1min
[CV 1/5] END svc__C=10.0, svc__gamma=10.0, svc__kernel=rbf;, score=0.349 total time= 1.8min
[CV 2/5] END svc__C=10.0, svc__gamma=10.0, svc__kernel=rbf;, score=0.349 total time= 1.6min
[CV 3/5] END svc__C=10.0, svc__gamma=10.0, svc__kernel=rbf;, score=0.353 total time= 1.8min
[CV 4/5] END svc__C=10.0, svc__gamma=10.0, svc__kernel=rbf;, score=0.353 total time= 1.7min
[CV 5/5] END svc__C=10.0, svc__gamma=10.0, svc__kernel=rbf;, score=0.351 total time= 1.7min


GridSearchCV(estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('svc', SVC(random_state=1))]),
             param_grid=[{'svc__C': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 10.0],
                          'svc__kernel': ['linear']},
                         {'svc__C': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 10.0],
                          'svc__gamma': [0.001, 0.01, 0.05, 0.1, 0.5, 1.0,
                                         10.0],
                          'svc__kernel': ['rbf']}],
             verbose=3)

In [47]:
svc_grid.best_params_

{'svc__C': 1.0, 'svc__gamma': 0.1, 'svc__kernel': 'rbf'}

In [48]:
svc_grid_pred = svc_grid.predict(X_test)

In [49]:
print(confusion_matrix(y_test, svc_grid_pred))

[[ 379  146  199  200   34]
 [  80 1306  177  149   62]
 [  63  131  746  246   47]
 [ 115  214  349  531   38]
 [  40   84   70   66  571]]


In [50]:
print(classification_report(y_test, svc_grid_pred))

              precision    recall  f1-score   support

         0.0       0.56      0.40      0.46       958
         1.0       0.69      0.74      0.71      1774
         2.0       0.48      0.61      0.54      1233
         3.0       0.45      0.43      0.44      1247
         4.0       0.76      0.69      0.72       831

    accuracy                           0.58      6043
   macro avg       0.59      0.57      0.57      6043
weighted avg       0.59      0.58      0.58      6043



## Decision Tree

In [51]:
pipe = Pipeline((
    ('std_sc', StandardScaler()), 
    ('dec_tree', DecisionTreeClassifier())
))

In [52]:
criterion = ['gini', 'entropy']

In [53]:
dec_tree_param = [{
    'dec_tree__criterion': criterion, 
    'dec_tree__max_depth': [2, 4, 6, 8, 10]
}]

In [54]:
dec_tree_grid = GridSearchCV(pipe, dec_tree_param)

In [55]:
dec_tree_grid.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=(('std_sc', StandardScaler()),
                                       ('dec_tree', DecisionTreeClassifier()))),
             param_grid=[{'dec_tree__criterion': ['gini', 'entropy'],
                          'dec_tree__max_depth': [2, 4, 6, 8, 10]}])

In [56]:
dec_tree_grid.best_estimator_

Pipeline(steps=[('std_sc', StandardScaler()),
                ('dec_tree', DecisionTreeClassifier(max_depth=10))])

In [57]:
dec_tree_grid_pred = dec_tree_grid.predict(X_test)

In [58]:
print(confusion_matrix(y_test, dec_tree_grid_pred))

[[ 250  206  256  198   48]
 [ 120 1160  251  168   75]
 [  88  155  675  244   71]
 [ 134  230  454  375   54]
 [  64  111  111   69  476]]


In [59]:
print(classification_report(y_test, dec_tree_grid_pred))

              precision    recall  f1-score   support

         0.0       0.38      0.26      0.31       958
         1.0       0.62      0.65      0.64      1774
         2.0       0.39      0.55      0.45      1233
         3.0       0.36      0.30      0.33      1247
         4.0       0.66      0.57      0.61       831

    accuracy                           0.49      6043
   macro avg       0.48      0.47      0.47      6043
weighted avg       0.49      0.49      0.48      6043



## RandomForestClassifier

In [60]:
RF = make_pipeline(RandomForestClassifier())
l = [*range(1, 11)]
param_grid_rfc = [{
    'randomforestclassifier__max_depth':l,
    'randomforestclassifier__max_features':[2, 3, 4, 5, 6]
}]
rf_grid = GridSearchCV(estimator=RF,
                     param_grid = param_grid_rfc,
                     n_jobs=-1)
rf_grid.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('randomforestclassifier',
                                        RandomForestClassifier())]),
             n_jobs=-1,
             param_grid=[{'randomforestclassifier__max_depth': [1, 2, 3, 4, 5,
                                                                6, 7, 8, 9,
                                                                10],
                          'randomforestclassifier__max_features': [2, 3, 4, 5,
                                                                   6]}])

In [61]:
rf_grid.best_estimator_

Pipeline(steps=[('randomforestclassifier',
                 RandomForestClassifier(max_depth=10, max_features=6))])

In [62]:
rf_pred = rf_grid.predict(X_test)
print(confusion_matrix(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

[[ 267  215  258  168   50]
 [  61 1297  222  124   70]
 [  52  159  775  196   51]
 [  91  258  438  405   55]
 [  27   87   98   49  570]]
              precision    recall  f1-score   support

         0.0       0.54      0.28      0.37       958
         1.0       0.64      0.73      0.68      1774
         2.0       0.43      0.63      0.51      1233
         3.0       0.43      0.32      0.37      1247
         4.0       0.72      0.69      0.70       831

    accuracy                           0.55      6043
   macro avg       0.55      0.53      0.53      6043
weighted avg       0.55      0.55      0.54      6043

